### ISSUE TITLE
Crashes upon loading previously saved patches

### ISSUE THREAD

**Issue by kade-t** [j4s0n-c/ISF-Synth-VCV#10]
I'm using the non-watermarked version that you sent me. I'm loading previously saved patches and more often than not I experience a crash as soon as I try to load the next save file. I'm using an external window to save my output, but the crash happens regardless of whether or not the external window is left open during the opening of the next save file. 

Attached is a log.txt of the most recent crash.
[log.txt](https://github.com/user-attachments/files/15528109/log.txt)

**Comment by j4s0n-c** [comment]
Nothing is really jumping out at us in that log. I wonder if it has to do with texture senders / Spout being active when VCV kills the old patch and loads the new one? We'll try to investigate further...

**Comment by j4s0n-c** [comment]
@kade-t I just tried opening a bunch of saved patches turning on Spout and testing before opening the next. I had no crashes. Are you using any other makers modules in these patches? Can you you narrow it down to specific patches or is it just any random ones that crash?

**Comment by kade-t** [comment]
I'm not sure why but I'm not having any crashes now. I was/am using ME by stoermelder as the only non-trowaSoft module.

**Comment by j4s0n-c** [comment]
Oh perfect! Intermittent problems are the most fun to try to solve. o_0
There has to be something like maybe other software running or loading patches from an external drive, or running a laptop on battery vs. plugged in, uhh...
Let me know if you are able to narrow it down. We'll leave the issue open for now just in case.

**Comment by j4s0n-c** [comment]
Issue seems to be resolved.
