### ISSUE TITLE
Initial install of modules triggered crashes on module browsing, 100% reproducible until full reinstall, now not reproducible

### ISSUE THREAD

**Issue by tmayshark** [j4s0n-c/ISF-Synth-VCV#12]
Just noting this, even though this is the epitome of an annoying and impossible for me to reproduce issue:

After first launch of VCV Pro 2 on Windows 11 w/the beta plugin sitting in /plugins, I did an `update all`, closed VCV, and came back in. At this point, bringing up the module browser would cause a complete crash of VCV within 1-2 seconds, 100% of the time, whether I was interacting with the browser, or just letting it sit there.

This problem persisted after removing the video modules from the filesystem entirely, persisted through a reinstall of VCV Pro 2, and then went away when I completely nuked the contents of the user folder and also did a reboot between installs of Pro 2.

I cannot definitively say that these video modules had anything to do with it; several other module updates happened at the same time, and I am unable to reproduce the crashes at all on a clean install after extensive thrashing with them.

I believe I retained the contents of the user folder I trashed; if this is a concern or if anyone else sees this issue, I can provide that.

**Comment by j4s0n-c** [comment]
Oof! I hope it wasn't our stuff but impossible to say at this point. If you still have the user folder you could try checking the log.txt file for anything strange. Glad you got it sorted out. Happy patching!

**Comment by j4s0n-c** [comment]
This seems, hopefully, unrelated to this plugin. Closing.
