### ISSUE TITLE
cv in's dont respond to video synth signals, just audio

### ISSUE THREAD

**Issue by evanh41** [j4s0n-c/ISF-Synth-VCV#2]
heya, 

so whenever i plug any video signal into a cv  in one something say an oscillator frequency or phase, 

I dont get any fm or bends associated with a normal video synth look. 

however, when I patch an audio lfo or oscillator, i get some movement. 

but nothing like the cool video rate stuff we're all used to.

**Comment by j4s0n-c** [comment]
New module "MOD" can displace one texture with another. Same as above. We might still add direct modulation inputs to other modules later but I think this takes care of it for now.
