### ISSUE TITLE
Jumps in ISFs that modify TIME

### ISSUE THREAD

**Issue by thomasvanta** [j4s0n-c/ISF-Synth-VCV#6]
TIME is a predefined float uniform to properly be able to reduce or increase speed without making the shader jump in time. I guess an integrator on the c++ side.
It would be useful to have different variations of that time in a vec4 uniform, for example:
TIME.x = what we already get as TIME.
TIME.y = half the speed of TIME
TIME.z = quarter
TIME.w = doble

The issue is very apparent on something like the animate_speed in GEN_SHAPE_MIX

**Comment by j4s0n-c** [comment]
@thomasvanta We've updated WAVE speed control to be smooth and added a phase reset button.
